behaviors:
  Hikaru:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32 #32 - 512
      buffer_size: 4096 #2048 - 409600
      learning_rate: 1e-3 #1e-5 - 1e-3
      epsilon: 0.3 #0.2
      lambd: 0.95 #0.95
      num_epoch: 5 #3-10
      learning_rate_schedule: linear 
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3 #1-3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 20 #5
    checkpoint_interval: 10000
    max_steps: 10000000
    time_horizon: 8 #32-2048
    summary_freq: 1000
    threaded: true
    self_play:
      save_steps: 1000
      team_change: 10000
      swap_steps: 500
      window: 20
      play_against_latest_model_ratio: 0.05
      initial_elo: 1200.0